apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-volume
data:
  application.conf: |
    akka {
      actor {
        typed {
          extensions = [
            "infrastructure.MillenniumFalconConfiguration$",
            "infrastructure.SlickSessionProvider$",
            "infrastructure.ServerConfiguration$"
          ]
        }
      }
    }
    cors {
      allow-generic-http-requests = on
      allowed-origins = ["*"]
      allow-credentials = on
      allowed-methods = ["GET", "POST", "HEAD", "OPTIONS"]
    }
    server {
      address = "0.0.0.0"
      port = 80
    }